### PR TITLE
Initial PR - Group by monitor status and filter by status

### PR DESCRIPTION
**Pull request by RobertByrnes**
Hi, Thank you for your response to my issue. I've opened this PR for you to see all the code changes I have made based on how we are using this tile on our dashboard.

This is not completed and ready to merge! (I wish first, to have your view on how you would see this being integrated into the existing code base).

There are some things I wish to make configurable first. It would be really handy to know - would you wish to preserve the original tile.blade.php and use the alternative in this PR as an optional one. Or just adopt the new view? (and the supporting back end changes).

Looking forward to hearing your thoughts....

### CODE REVIEW

**Comment by vinevax** [comment]
Hi, I would add your view as an additional option, because for only a few monitors I like my view a bit more, but if I'd have more monitors (like in your screenshot) I would choose your view.  So, maybe add a config option to switch between my view (e.g. basic) and yours (e.g. advanced)?

**Comment by RobertByrnes** [comment]
Hi, That's what I thought too....will get the option switching bits of code in there and resubmit the request....

**Comment by RobertByrnes** [comment]
Hi @vinevax 

The changes are now there to allow a switch between 'original' and 'alternative' blade views from the dashboard.php config file.

Have now updated the CHANGELOG and README aswell...


Cheers

**Comment by vinevax** [comment]
Thanks for the great work @RobertByrnes. I've just published a new release. Note: I had to upgrade the default Alpine.js version from 2 to 3, so I've made this a new major release (3.0.0) and added instructions for upgrading Alpine.

**Comment by RobertByrnes** [comment]
@vinevax Nice! Missed that bit! Awesome, and thank you for encouraging collaboration 😀

**Pull request merged**
